I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 843, in script
    if $ corealmondaycount == 0:
  File "game/script.rpy", line 843, in <module>
    if $ corealmondaycount == 0:
NameError: name 'corealmondaycount' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 843, in script
    if $ corealmondaycount == 0:
  File "/Applications/renpy-7.0.0-sdk/renpy/ast.py", line 1729, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-7.0.0-sdk/renpy/python.py", line 1943, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.0.0-sdk/renpy/python.py", line 1936, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 843, in <module>
    if $ corealmondaycount == 0:
NameError: name 'corealmondaycount' is not defined

Darwin-16.7.0-x86_64-i386-64bit
Ren'Py 7.0.0.196
Digiwarped_01 1.0
Sat Aug  4 23:40:04 2018
